function Home() {
    return (
        <main>
            <h1>Home</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea ipsum perferendis eos earum. Ipsam, iste ratione temporibus eveniet iure quo consectetur numquam officia? Commodi quisquam eaque, tenetur vel recusandae illo?</p>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Pariatur aliquid, omnis hic explicabo eius molestias harum deserunt fugiat suscipit nihil magnam modi neque ad rerum voluptate assumenda ab sequi eum impedit iusto amet sapiente nostrum a consequatur? Doloremque dolor incidunt corporis rem maiores? Optio officia nulla quos, debitis saepe pariatur, dolore cum non rerum mollitia nisi ullam quisquam magni quam? Incidunt consequuntur repellat delectus rerum repellendus. Quae, necessitatibus! Vitae mollitia nisi aspernatur perferendis eos unde, adipisci quia voluptates atque animi reprehenderit molestias rerum necessitatibus expedita placeat cupiditate consequatur libero beatae earum nam est ipsam ea ratione optio. Fugit fuga nam dignissimos enim dolorem deserunt quo blanditiis omnis laborum accusantium sed iusto repudiandae earum similique eligendi numquam illo inventore itaque odit delectus vitae laboriosam, ad voluptatum! Incidunt inventore commodi rerum nisi, ratione id debitis deserunt molestias amet illo? Excepturi recusandae, enim aut vero ratione veniam error voluptate ullam. Iste earum veniam repellendus, vero amet, vitae eaque quisquam nemo neque numquam saepe voluptate! Blanditiis enim asperiores et obcaecati quod nulla quidem? Praesentium voluptate possimus corrupti eaque aliquam consequuntur explicabo repellendus nobis, reprehenderit dolor, magnam aperiam consectetur pariatur ex? Vel eligendi architecto odio laborum dolor. Possimus magni consectetur voluptatum nesciunt! Voluptas, minus asperiores.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vitae earum nulla dicta? Illum voluptatibus aliquam consectetur quas doloremque numquam placeat quos magni maiores, repellendus sunt iure odit quidem inventore, tempora ex possimus officia impedit? Voluptatem maiores, ullam officiis est aspernatur ea asperiores inventore et incidunt numquam dignissimos excepturi enim temporibus optio, repudiandae accusamus beatae cum quisquam? Est error quam et, soluta quo saepe aliquid animi alias sit ab distinctio, repellendus vitae exercitationem optio fugiat. Eum odio a asperiores incidunt neque labore dolor non! Maiores, incidunt? Ab, consequatur eum! Beatae magni delectus aliquid exercitationem vero sunt quidem veritatis distinctio possimus. Corrupti!</p>
        </main>
    )
}

export default Home